### ISSUE TITLE
Thermal Dynamics 171 crash on startup

### ISSUE THREAD

**Issue by pikkon38** [CoFH/Feedback#1162]
Currently my large modpack crashes when updating thermal dynamics from 161 to 171. Thermal Foundation and Thermal Dynamics were the only mods needing to be updated. Updating Thermal Foundation and leaving 161 Dynamics has no issues. Adding 171 causes client crashes on startup

http://pastebin.com/9KvYCSdH

Key take away from crash report: 
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: cofh/thermaldynamics/duct/entity/TileTransportDuctCrossover

**Comment by skyboy** [comment]
Another mod is probably interfering with TD. Try loading with only CoFH mods to verify.

**Comment by pikkon38** [comment]
I did verify the CoFH mods do indeed load fine without other mods. But the only way I can repro the crash is updating Thermal Dynamics. And the crash log only gives me info about TD crashing. I am going through and testing removal and updating any mods that might need to be update, and so far nothing has solved the issue.

**Comment by skyboy** [comment]
Then there's nothing that can be done here to fix the crash. Another mod (or mods, if multiple mods are editing our classes) is causing the class to fail to load, and the only way you can play is to either not update TD or to remove the other mod.

**Comment by AlienXtream** [comment]
was any progress made on resolving this?
