### ISSUE TITLE
MFR downloads page needs update for CofHCore 3.0.0RC1-1

### ISSUE THREAD

**Issue by codewarrior0** [CoFH/Feedback#139]
Using MineFactoryReloaded-[1.7.10]2.8.0RC6-5, CofHCore 3.0.0RC1-1

Error when entering world:
```
java.lang.NoSuchMethodError: cofh.core.util.fluid.FluidTankAdv.setLock(Lnet/minecraftforge/fluids/Fluid;)V
	at powercrystals.minefactoryreloaded.tile.machine.TileEntityComposter.<init>(TileEntityComposter.java:28) ~[TileEntityComposter.class:?]
```
(while constructing a composter for neiintegration)

`setLock` was changed from returning `void` to returning `this`.

**Comment by codewarrior0** [comment]
Found MineFactoryReloaded-[1.7.10]2.8.0RC7-71 under 'see all downloads' for MFR. This version works with CofHCore 3.0.0RC1-1. The main downloads page should offer this version of MFR as the current version, as the older one doesn't work with the new CofHCore.

**Comment by codewarrior0** [comment]
The downloads page appears to be fixed. Thanks!
